# Generated by Django 3.0.5 on 2020-05-16 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20200513_1718'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['last_name', 'first_name'], 'permissions': (('can_crud_author', 'Can create, update, delete author'),)},
        ),
    ]
