# Generated by Django 3.0.5 on 2020-05-26 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20200516_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('fr', 'French'), ('de', 'German'), ('es', 'Spanish'), ('fa', 'Farsi'), ('vi', 'Vietnamese')], default='en', help_text='Select language for this book', max_length=2),
        ),
    ]
